language: node_js
cache:
  yarn: true
  directories:
    - "node_modules"
sudo: required
node_js:
  - '10'
services:
  - docker

env:
  matrix:
    - PACKAGE=@herajs/client
    - PACKAGE=@herajs/crypto
    - PACKAGE=@herajs/wallet
  
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"
  - docker run -d -p 7845:7845 --name aergosvr aergo/node:1.1.0-rc aergosvr --config /aergo/testmode.toml

before_script:
  - yarn run lerna run prepublish
  - yarn run lerna run build
  - sleep 10

script: yarn run lerna run test --scope $PACKAGE --stream

after_failure:
  - docker logs aergosvr

branches:
  except:
    - /^v\d+\.\d+\.\d+$/